### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/mgattozzi#3]
It would be good to have an RSS feed so that people can subscribe directly to new updates

**Comment by tfausak** [comment]
I see that you do have a feed (<https://mgattozzi.com/feed>). One thing that would help me out a lot is adding `<pubDate>` elements to each entry. Would you mind adding that?

**Comment by mgattozzi** [comment]
Hey @tfausak that shouldn't be too hard since I already have the dates written out in the description so I can add that field!

**Comment by mgattozzi** [comment]
@tfausak I just updated it so you should have the pubDate field in there now!

**Comment by tfausak** [comment]
Fantastic, it works great! Thanks for the fast turnaround :+1:

**Comment by mgattozzi** [comment]
No problem it was an easy use of my lunch break! :D
