### ISSUE TITLE
Question about Diesel Powered Rocket's lazy static pooling

### ISSUE THREAD

**Issue by TheDan64** [mgattozzi/mgattozzi#9]
Hi there, this was a very informative post! I hope it gets a follow up in the future!

I was wondering if would it be possible or even at all a good idea, to use Rocket's [managed state](https://rocket.rs/guide/state/#managed-state) functionality instead of a lazy static for the connection pool? You'd have to manually get a connection from the pool in your endpoints, but it might save you the manual impl of FromRequest and lazy static boilerplate if I'm understanding managed state correctly.

**Comment by mgattozzi** [comment]
This was written before managed state was available. While it still works I think you could easily switch over to use that instead of you wanted. I haven't played around with it enough to know for sure though. Apologies for getting to you so late. I'm on my two week training with the national guard so I don't have as much time to look at it answer questions till I'm back.

**Comment by mgattozzi** [comment]
I also noticed you're in Boston MA. I'll be at the next meet up there this June so if you can stop by and find me and we can talk more it hack on this for fun!

**Comment by TheDan64** [comment]
No problem! Yeah totally, if I can make it I will be sure to stop by!

**Comment by mgattozzi** [comment]
Awesome! Looking forward to it!

**Comment by TheDan64** [comment]
I wasn't able to make it unfortunately, but I wanted to mention that Sergio added a database section under managing state with diesel pools: https://github.com/SergioBenitez/Rocket/blob/master/site/guide/state.md

**Comment by mgattozzi** [comment]
Ah excellent! I was going to rewrite a lot of the code on my site once the new version of Rocket comes out and this was one of them. I'll probably have to update an article or two as well
